"""Add Name

Revision ID: 9d90eca8cc2d
Revises: 9c1bc1f050c2
Create Date: 2019-05-03 17:25:02.378318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d90eca8cc2d'
down_revision = '9c1bc1f050c2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_visit', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_visit', 'name')
    # ### end Alembic commands ###
